version: "3"

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    hostname: mongodb
    networks:
      data-loading:
        aliases:
          - mondodb
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "512M"

networks:
  data-loading:
    driver: "bridge"